Issue#8 タイマーを適用する
jphacks/D_2011 pull request #45
Opened 2020-11-17 16:54 UTC by Tomoya113

# 変更点
ミーティング中に使用するタイマーを管理するMeetingTimerクラスを実装

2020-11-17 16:59 UTC, mizucoffee requested changes
ざっと見た感じ動きそうー
ぜひ既存コードに適用していただきたく🙏

2020-11-17 17:00 UTC, Tomoya113 commented
@mizucoffee 
ミーティングの管理とアジェンダの管理を一個のクラスで行ってるから、MeetingTimerクラスのインスタンスをMeetingRouterとAgendaRouterの両方から呼び出したいんだけど、何かいい方法ある？現状はMeetingRouterとAgendaRouterがファイルを分けて実装されているので、呼び出しが難しい気がする。

2020-11-17 17:06 UTC, mizucoffee commented
@Tomoya113 シングルトンにする or APIを１つのファイルにまとめるかなぁ

2020-11-17 18:10 UTC, Tomoya113 commented
@mizucoffee 
一旦APIを一つにまとめて実装してみるわ〜

2020-11-17 18:12 UTC, mizucoffee commented
@Tomoya113 MeetingTimerを1つだけ生成するってことやんな？
やったらシングルトンで良い気がするんだけどどうかしら

2020-11-17 18:17 UTC, Tomoya113 commented
@mizucoffee 
MeetingTimerのインスタンスは1ミーティングにつき1つだけ。
勉強不足でシングルトンの意味がいまいちわかってないんだけど、この場合どこをシングルトンにする感じですか

2020-11-17 18:19 UTC, mizucoffee commented
ミーティング単位なのか。ってことはAPIを1つのファイルにしたらグローバルにハッシュを作る感じ？
シングルトンは1つしかインスタンスを作れないクラス（超ざっくり）

2020-11-17 18:21 UTC, Tomoya113 commented
そうそう。MeetingRouterとAgendaRouterのどちらからもアクセスできるようなスコープでMeetingTimerを初期化したい

2020-11-17 18:37 UTC, mizucoffee commented
@Tomoya113 ZoomManagerの管理下に置くのが一番簡単な気がしてるがflutter対応中なので出来ないな...

2020-11-17 18:46 UTC, Tomoya113 commented
@mizucoffee 
ZoomManagerにMeetingTimerをマージするって感じ？たしかに悪くなさそう？

2020-11-17 18:55 UTC, Tomoya113 commented
@mizucoffee 
一旦仮でマージしたやつ実装するわ

2020-11-18 11:54 UTC, Tomoya113 commented
@mizucoffee 
一旦ZoomManagerにMeetingTimerを統合してみても良い？

2020-11-19 04:59 UTC, mizucoffee commented
@Tomoya113 OK

2020-11-19 16:22 UTC, Tomoya113 commented
@mizucoffee 書けた気がするうううう

2020-11-20 06:50 UTC, Tomoya113 commented
@mizucoffee これは待っておけば良い感じ？

2020-11-21 02:58 UTC, mizucoffee approved these changes
マージしてから調整します

2020-11-21 03:10 UTC, mizucoffee requested changes
API消えてる

2020-11-21 11:33 UTC, mizucoffee commented
とりあえずCloseしときます

2020-11-21 11:33 UTC, closed without merging