Issue #32 linkno
jphacks/D_2011 pull request #46
Opened 2020-11-19 11:04 UTC by penguin4731

2020-11-19 11:07 UTC, penguin4731 commented
linkの削除 zoom_idとzoom_passの追加をしました

VIewのinviteのページのリンクだけ、zoomのUrlになるように文字列組んでほしいです。（前に送っていただいたのが行方不明になってしまいました 😭）
それぞれ、`@meeting.zoom_id`と`@meeting.zoom_pass`で取得可能かと思います。

2020-11-20 03:56 UTC, mizucoffee requested changes
@penguin4731 下記形式になるので対応していただけるとー！
`zoommtg://zoom.us/join?confno=<ミーティングID>&pwd=<ミーティングパスワード>`

2020-11-20 12:56 UTC, penguin4731 commented
@mizucoffee Zoomのマジックリンクの実装しました！再レビューお願いします🙇‍♂️

2020-11-20 14:16 UTC, mizucoffee approved these changes
LGTM

2020-11-20 14:16 UTC, merged