MeetingTimerの開始タイミングを自由にする
jphacks/D_2011 pull request #65
Opened 2020-11-21 12:50 UTC by Tomoya113

# 関連Issue
#64 
# 内容
Meetingを開始予定時間よりも早く開始できるようにしました。

2020-11-21 12:51 UTC, Tomoya113 commented
@mizucoffee 
開始時間を遅らせるメソッドも実装したほうがええですか？

2020-11-22 12:05 UTC, mizucoffee commented
@Tomoya113 
定義されている開始時刻を使わないタイマーにしてほしい！
開始時刻になっても始まらなくてOK

ユーザーが任意のタイミングで開始した時刻からn分間っていう数え方でお願いします🙇‍♀️

2020-11-22 12:41 UTC, mizucoffee requested changes
@Tomoya113
定義されている開始時刻を使わないタイマーにしてほしい！
開始時刻になっても始まらなくてOK

ユーザーが任意のタイミングで開始した時刻からn分間っていう数え方でお願いします🙇‍♀️

2020-11-23 15:59 UTC, mizucoffee requested changes

2020-11-23 15:59 UTC, mizucoffee commented on src/meeting_timer.rb
> +      p 'アジェンダを登録してください'
returnしないとだめそう

2020-11-23 15:59 UTC, mizucoffee commented on src/meeting_timer.rb
>      @time += @methods.first[:time]
@timeは加算せずに開始時刻を保持した方がいいかも。
時間になる前に次の議題に移った時、あまり時間が次の議題時間に加算されそう。

2020-11-23 15:59 UTC, mizucoffee commented on src/meeting_timer.rb
>        while Time.now.to_i <= @time
`Time.now.to_i <= @time + @methods.first[:time]` 的な

2020-11-23 15:59 UTC, mizucoffee commented on src/meeting_timer.rb
>        while Time.now.to_i <= @time
同じく

2020-11-23 16:13 UTC, Tomoya113 commented
@mizucoffee 
@durationを新たに追加して、@timeに追加していく感じにしました。
@timeが開始時刻だけを保持した場合、２つ目のアジェンダがいつ終わるかが保持できないため

2020-11-23 16:14 UTC, mizucoffee commented
言われてみれば確かに

2020-11-23 16:18 UTC, mizucoffee approved these changes
脳内インタプリタの限界を感じたので一旦マージしてテスト書いてみる

2020-11-23 16:26 UTC, mizucoffee requested changes

2020-11-23 16:26 UTC, mizucoffee commented on src/meeting_timer.rb
> +      p 'アジェンダを登録してください'
@Tomoya113 これどうなった？

2020-11-23 16:51 UTC, mizucoffee approved these changes

2020-11-23 16:51 UTC, merged